### ISSUE TITLE
 ERROR An error occurred setting up the project: Cannot run program "npx": CreateProcess error=2, El sistema no puede encontrar el archivo especificado

### ISSUE THREAD

**Issue by mikelemus27** [tomthought/react-native-init-shadow#16]
PS C:\23A-cljweb\23A-cljsapp\shadow-cljs-apps\win-scljs-apps> npx react-native-init-shadow@latest rn1
2023-04-10T06:01:44,278Z INFO Setting up project 'rn1'
2023-04-10T06:01:44,284Z INFO npx react-native@latest init Rn1 --directory rn1
2023-04-10T06:01:44,350Z ERROR An error occurred setting up the project: Cannot run program "npx": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
java.io.IOException: Cannot run program "npx": CreateProcess error=2, El sistema no puede encontrar el archivo especificado
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at crusta.core$exec.invokeStatic(core.clj:43)
        at crusta.core$exec.doInvoke(core.clj:22)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at react_native_init_shadow.core$exec.invokeStatic(core.clj:39)
        at react_native_init_shadow.core$exec.doInvoke(core.clj:36)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at react_native_init_shadow.core$fn__6002.invokeStatic(core.clj:64)
        at react_native_init_shadow.core$fn__6002.invoke(core.clj:61)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at react_native_init_shadow.core$_main.invokeStatic(core.clj:170)
        at react_native_init_shadow.core$_main.doInvoke(core.clj:145)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at react_native_init_shadow.core.main(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 18 common frames omitted

**Comment by tomthought** [comment]
Hi there, please make sure you have installed the necessary dependencies. You'll need to have npm/npx installed, along with a few others (shadow-cljs, CocoaPods, and Babashka).

**Comment by mikelemus27** [comment]
yes i am working on windows  and that is  why  CocoaPods is the only missing depndendencie, unless it is mandatory, but npx npm babashka  and shadow-cljs  are installed

**Comment by mikelemus27** [comment]
maybe is about this
https://medium.com/@alvareztech/soluci%C3%B3n-createprocess-error-2-el-sistema-no-puede-encontrar-el-archivo-especificado-en-android-30e5d07fbee0

a misconfiguration of JAVA_HOME and  add it  to path , but also tried that

**Comment by tomthought** [comment]
Possibly. I don't normally develop on Windows so can't offer much help if it's a Windows environment issue. If it's still not working you could run the commands directly and see if it works. This project is essentially just a wrapper around `npx react-native init` and then some cljs files are copied into a `src` directory, and a `shadow-cljs.edn` file is placed in the project root.
